### ISSUE TITLE
Consider duplicating repo for a generic project

### ISSUE THREAD

**Issue by waldoj** [codeforamerica/PoliceOpenDataCensus#4]
I'm using this [for a project of my own](https://github.com/opendata/Open-Data-Census), which of course necessitates hacking out all of the parts specific to the police open data census, your GA token, your hard-coded GH URL, etc. It occurs to me, while doing this, that it may be helpful to abstract your own work here as a general platform. Consider naming this something, putting it in its own repository, and folks like me who want to use it can modify it to make it more generic, so that it would be easier for others to use.

**Comment by waldoj** [comment]
Just a reminder that I'd be happy to contribute to this with all of the modifications that I've made, and make some more to further abstract it for general use. And if y'all don't want to do this, I can publish it on my org's repo. I'd just rather see you get the credit. :)

**Comment by bengolder** [comment]
@waldoj just a heads up that the fellowship recently ended and @creade is on vacation, so you may not hear back quickly.

**Comment by waldoj** [comment]
Oh, hey, that's wildly useful information. :) I'll give it a couple of weeks, then. Thank you, Benjamin!

**Comment by creade** [comment]
Hey @waldoj !

My immensest apologies for the delay in getting on this. I've hand forked this to https://github.com/codeforamerica/OpenOpenDataCensus, I'll start pulling the police-centric stuff I know of off it, but feel to push your changes up too (I added you as a contributor.)

And seriously thank you again for reaching out and helping on this, I'm excited to see what happens with it!

**Comment by waldoj** [comment]
Thank you! I've made a whole mess of changes, with more planned, and I've been eager to fork those off to a stand-alone project. Open Open Data Census it is! Thanks, @creade. :)
